function result = getRequestCharge(obj)
% GETREQUESTCHARGE Gets number of index paths (terms) generated by the operation
% Returns a double

% Copyright 2019 The MathWorks, Inc.

result = obj.Handle.getRequestCharge();

end
